services:
  php:
    volumes:
      - ./:/var/www

  nginx:
    volumes:
      - ./docker/nginx/local.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/

  redis:
    ports:
      - "6379:6379"

networks:
  coasters-network:
    driver: bridge

volumes:
  coasters-volume: